---
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

extends: airbnb

env:
  amd: true
  browser: true
  es2020: true
  node: true

# http://eslint.org/docs/rules/

# React Specific
react/jsx-filename-extension:
  - error
  - extensions:
      - .jsx
      - .js
