language: node_js
node_js:
  - 10.17.0
python:
  - 3.6.7
env:
  matrix:
    secure: gSb+5hzjOEsBsrJRIb8x2pQF/Y/yB4b1d1OGW2BkXCLECwFfk/UCCpE1LIWLeK2XJpuF9H/yewZFc2lrgYsM1NI1Wn33BcOFWuvCq3uyLFlpdiB5jKNXvLYA6xmudwbvWPh9AjubN2IJplatF2EAMyf1JjgOX+M3lEWOGqiaOYMLjP+8PphInhbscMDWJb2ni601Q+iBDtEkhwLPWVIzz0gY3EyXta0YbtbiWvjhsFE9NYf2MuB/s9xb3UK09jq2bBtD4M80+ppzYUTmq8s3GzTPqpPm0vww67xkMUPA4tkgygFNwYYETeytLL9bdyDY8PitJfGn26qoZTPSy6z2TOJEmEVhf077Tk25FrJcIjFltQ3Nne/NYczTwFqUrrXNoLPgplm4zMy3LZZKweL11juMmbXmyTZ3fywGqJ8RwKPEKO3Qeuv0xtsPiAc1qmh6bC5Y7E65G5rDj77ei+7BFc12nSjqBCa0rLx1iC47fzeGTwWKCIb6A6tJbr6mRVkRbcP7M9rQ/UMWYskrFLgGbvrgHX0Hn28uHS76CNBAwvh0eQk3iG2iOIZ9GVC32Lh66daLL9noDhTiDGUdmp6q7ofG8jtNDPvnqF6CXgUBgpE8GGDd6paTmHT4rIiKLUI42sQwOzfIhwt7exckspqyZvvZbnkYg/Yk7bR8vTHLZ0M=
cache:
  directories:
  - "~/.npm"
  - ".jest"
before_install:
- npm install -g npm@latest
- npm install -g expo-cli

stages:
- build
- test
#- name: deploy staging
#  if: branch = develop
#- name: deploy production
#  if: branch = master
jobs:
  include:
  - stage: test
    before_install:
      - cd ./backend
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt
      - pip3 install pytest
      - pip3 install pytest-timeout
      - pip3 install codecov
    script:
      - cd frontend
      - npm ci
      - npx jest --ci --passWithNoTests
      - cd ../backend
      - python3 -m pytest --timeout 600 test/test_SQLQueue.py
    after_success:
        - codecov # submit coverage


#  - stage: deploy staging
#    script:
#    - cd frontend
#    - npm ci
#    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
#    - npx expo publish --non-interactive --release-channel staging
#  - stage: deploy production
#    script:
#    - cd frontend
#    - npm ci
#    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
#    - npx expo publish --non-interactive --release-channel production
